---
- name: Cteate Tenant
  hosts: all
  connection: local
  gather_facts: no
  vars:
    aci_login: &aci_login
      hostname: '{{ inventory_hostname }}'
      username: "{{ lookup('env', 'ANSIBLE_NET_USERNAME') }}"
      password: "{{ lookup('env', 'ANSIBLE_NET_PASSWORD') }}"
      validate_certs: no
    tenant_name: '{{ avx_tenant }}'
    input: '{{awx_input}}'


  tasks:

  - name: Create Tenant
    aci_tenant:
      <<: *aci_login
      tenant: '{{ item.name }}'
      state: present
    delegate_to: localhost
    with_items: "{{ input }}"
