- name: Customer Tenant Deployment - Basic Tenant\BD\VRF\VID\EPG\AEP-Assignment
  hosts: all
  connection: local
  gather_facts: no
  vars:
    aci_login: &aci_login
      hostname: '{{ inventory_hostname }}'
      username: "admin"
      password: "ciscopsdt"
      validate_certs: no
    tenant_name: '{{ avx_tenant }}'
    tenant_desc: '{{ avx_tenant_desc }}'

  tasks:
  - name: Create Tenant
    aci_tenant:
      <<: *aci_login
      tenant: '{{ tenant_name }}'
      description: '{{ tenant_desc }}'
      state: present
    delegate_to: localhost
