- name: Customer Tenant Deployment - Basic Tenant\BD\VRF\VID\EPG\AEP-Assignment
  hosts: all
  connection: local
  gather_facts: no
  vars:
    aci_login: &aci_login
      hostname: '{{ inventory_hostname }}'
      username: "{{ lookup('env', 'ANSIBLE_NET_USERNAME') }}"
      password: "{{ lookup('env', 'ANSIBLE_NET_PASSWORD') }}"
      validate_certs: no
    customer_id: '{{ _customer_id }}' # i.e. 100
    tenant_name: 'TEN_{{ _tenant_shortname|upper }}' # i.e. ABC

#    vrf_name: '{{ _vrf_name|upper }}' # i.e. VRF_ABC
#    bd_name: '{{ _bd_name|upper }}' # i.e. BD_ABC_XYZ
#    epg_name: '{{ _epg_name|upper}}' # i.e. EPG_ABC_XYZ
#    vlan_id: '{{ _vlan_id }}' # number
#    epg_aix: '{{ _epg_aix}}' # TRUE/FALSE...
#    epg_tdi: '{{ _epg_tdi}}' # TRUE/FALSE...
#    epg_esx: '{{ _epg_esx}}' # TRUE/FALSE...
#    epg_hpv: '{{ _epg_hpv}}' # TRUE/FALSE...
#    epg_bm: '{{ _epg_bm}}' # TRUE/FALSE...
#    epg_l2: '{{ _epg_l2}}' # TRUE/FALSE...
#    epg_fw: '{{ _epg_fw}}' # TRUE/FALSE...
#    epg_f5: '{{ _epg_f5}}' # TRUE/FALSE...
    
#    app_profile: 'APP_NET_CENTRIC' # statically configured on APIC
#    aep_bm_name: 'AEP_Bare_Metal_Domain' # statically configured on APIC
#    aep_esx_name: 'AEP_ESX_Domain'
#    aep_hpv_name: 'AEP_HPV_Domain'
#    aep_tdi_name: 'AEP_TDI_Domain'
#    aep_aix_name: 'AEP_AIX_Domain'
#    aep_l2_name: 'AEP_L2_Domain'
#    aep_fw_name: 'AEP_FW_Domain'
#    aep_f5_name: 'AEP_F5_Domain'

  tasks:
  - name: Create Tenant uni/tn-'{{ tenant_name }}'
    aci_tenant:
      <<: *aci_login
      tenant: '{{ tenant_name }}'
      description: 'Customer {{tenant_name|upper}}'
      state: present
    delegate_to: localhost
