- name: Customer Tenant Deployment - Basic Tenant\BD\VRF\VID\EPG\AEP-Assignment
  hosts: all
  connection: local
  gather_facts: no
  vars:
    aci_login: &aci_login
      hostname: '{{ inventory_hostname }}'
      username: "admin"
      password: "ciscopsdt"
      validate_certs: no
    mytoken: "{{awx_mytoken}}"
    myroom: "{{awx_myroom}}"
    
  tasks:


  - name: Query all tenants
    aci_tenant:
      <<: *aci_login
      state: query
    register: all_tenants
    delegate_to: localhost   
        
  - name: Cisco Webex Teams - Text Message to a Room
    community.general.cisco_webex:
      recipient_type: roomId
      recipient_id: "{{myroom}}"
      msg_type: markdown
      personal_token: "{{ mytoken }}"
      msg: "{{all_tenants}}"
    register: results
    
    
  - name: Create a subnet list item
    set_fact:
      array_content: "{{ item['fvTenant']['attributes']['name'] }}" 
    with_items: 
      - "{{ results['imdata'] }}"
    register: array_of_contents      
      
      
  - debug:
      var: array_of_contents     