- name: Dele a tenant / vars from AWX
  hosts: all
  connection: local
  gather_facts: no
  vars:
    aci_login: &aci_login
#      hostname: '{{ inventory_hostname }}'
      hostname: "sandboxapicdc.cisco.com"
      username: "admin"
      password: "ciscopsdt"
      validate_certs: no
    tenant_name: '{{awx_tenant}}'
    
  tasks:

  - name: Delete a tenant
    aci_tenant:
      <<: *aci_login
      tenant: '{{tenant_name}}'
      state: absent
    delegate_to: localhost