- name: Dele a tenant / vars from AWX
  hosts: all
  connection: local
  gather_facts: no
  vars:
    aci_login: &aci_login
      hostname: '{{ inventory_hostname }}'
      username: "{{ lookup('env', 'ANSIBLE_NET_USERNAME') }}"
      password: "{{ lookup('env', 'ANSIBLE_NET_PASSWORD') }}"
      validate_certs: no
    tenant_name: '{{awx_tenant}}'
    
  tasks:

  - name: Delete a tenant
    aci_tenant:
      <<: *aci_login
      tenant: '{{tenant_name}}'
      state: absent
    delegate_to: localhost