- name: Customer Tenant Deployment - Basic Tenant\BD\VRF\VID\EPG\AEP-Assignment
  hosts: all
  connection: local
  gather_facts: no
  vars:
    aci_login: &aci_login
#      hostname: '{{ inventory_hostname }}'
      hostname: "sandboxapicdc.cisco.com"
      username: "admin"
      password: "ciscopsdt"
      validate_certs: no
    mytoken: "{{awx_mytoken}}"
    myroom: "{{awx_myroom}}"
    
  tasks:


  - name: Query all tenants
    aci_tenant:
      <<: *aci_login
      state: query
    register: all_tenants
    delegate_to: localhost   
    
    
  - name: Create a subnet list item
    set_fact:
         array_content: "{{ item['fvTenant']['attributes']['name'] }}" 



    with_items: 
      - "{{all_tenants['current'] }}"
    register: array_of_contents      
      
      # 
      
#  - debug:
#      var: array_of_contents
      
      
  - name: Make a list with all the subnet items
    set_fact: 
         data_struc: "{{ array_of_contents.results | map(attribute='ansible_facts.array_content') | list }}"


  - debug:
      var: data_struc

  - debug:
      var: "{{data_struc | to_nice_yaml (indent=2)}}"

       
  - name: Cisco Webex Teams - Text Message to a Room
    community.general.cisco_webex:
      recipient_type: roomId
      recipient_id: "{{myroom}}"
      msg_type: text
      personal_token: "{{ mytoken }}"
      msg: "{{data_struc | to_nice_yaml (indent=2)}}"
    register: results      